/**
 * Create Connection Tool
 *
 * Creates a new connection (credentials/endpoint to a third-party service)
 * that automation steps can reference.
 */

import { z } from "zod";
import {
  withStandardDecorators,
  getApiClient,
  createToolResult,
  createToolResultError,
  CAPTURE_RAW_HTTP_RESPONSE,
  type ToolDefinition,
  type HttpResponse,
  type ProblemDetails,
} from "@umbraco-cms/mcp-server-sdk";
import type { getUmbracoAutomateManagementAPI } from "../../../api/generated/umbracoAutomateManagementApi.js";
import { postConnectionsBody } from "../../../api/generated/umbracoAutomateManagementApi.zod.js";

type ApiClient = ReturnType<typeof getUmbracoAutomateManagementAPI>;

const outputSchema = z.object({
  message: z.string(),
  id: z.string(),
});

const createConnectionTool = {
  name: "create-connection",
  description:
    "Creates a new connection — a named set of credentials/endpoint settings (e.g. an API key and base URL) that automation steps can reference by alias. `type` must match one of the aliases returned by the catalogue's connection-types listing, and `settings` must satisfy that type's settingsSchema. The new connection's id is generated by the server and returned here — use test-connection afterwards to confirm the credentials actually work.",
  inputSchema: postConnectionsBody.shape,
  outputSchema: outputSchema.shape,
  slices: ["create"],
  annotations: {},
  handler: async ({ alias, name, type, settings }) => {
    const client = getApiClient<ApiClient>();
    const response = (await client.postConnections(
      { alias, name, type, settings },
      CAPTURE_RAW_HTTP_RESPONSE
    )) as unknown as HttpResponse<ProblemDetails | void>;

    if (response.status === 201) {
      const locationHeader =
        response.headers?.["location"] || response.headers?.["Location"];
      let createdId = "";
      if (locationHeader) {
        const idMatch = locationHeader.match(/connections\/([a-f0-9-]+)$/i);
        if (idMatch) {
          createdId = idMatch[1];
        }
      }
      return createToolResult({
        message: "Connection created successfully",
        id: createdId,
      });
    }

    const errorData: ProblemDetails = (response.data as ProblemDetails) || {
      status: response.status,
      detail: response.statusText,
    };
    return createToolResultError(errorData);
  },
} satisfies ToolDefinition<typeof postConnectionsBody.shape, typeof outputSchema.shape>;

export default withStandardDecorators(createConnectionTool);
